AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - test/**/*_test.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
